### PR TITLE
Add bucket and user quotas as metrics

### PR DESCRIPTION
**Pull request by danielpalstra**
I've added the quota sizes of both the buckets and the users owning the buckets as metrics. With help of these metrics one can monitor bucket sizes related to quotas if set.

### CODE REVIEW

**Comment by k0ste** [comment]
Thanks, Daniel.
I was schedule for myself add quota support to this project, but still on start

My suggestions is:

1. Move quota requests to `_get_quota_usage(self, bucket)` function and call it from `collect()`.
2. Perform request with prepared args for python2 compat:
```python
for bucket in rgw_bucket:                                                       
    quota_args = "quota&uid={0}&quota-type=user".format(bucket['owner'])
    bucket["user_quota"] = self._request_data(query='user', args=quota_args)    
```
3. Also, I think exporter should have quotas for users (`admin/user?list`) per user (`admin/user?quota&uid={uid}&quota-type=user`), and for buckets (`admin/user?quota&uid={uid}&bucket={bucket}k&quota-type=bucket`).

**Comment by danielpalstra** [comment]
Thank you for the feedback @k0ste.

1+2. I will implement the suggested changes and refactor the code.
3. I wasn't aware of the `admin/user?list` endpoint (do the docs mention the list attribute?). I will split this part so user and bucket quotas can be retrieved separately.

**Comment by k0ste** [comment]
> I wasn't aware of the admin/user?list endpoint (do the docs mention the list attribute?). I will split this part so user and bucket quotas can be retrieved separately.

This feature is implemented in https://github.com/ceph/ceph/pull/25073, then backported to luminous https://github.com/ceph/ceph/pull/30984 and mimic https://github.com/ceph/ceph/pull/31754.

But, for compatible reasons metadata query may be implemented also, see https://github.com/cernceph/ceph-scripts/pull/25#pullrequestreview-365036622 conversation about this part and query examples (this is also undocumented).

**Comment by danielpalstra** [comment]
Based on the suggestions I've made some changes to the code. A summary

* All f strings are replaced with the prepared args to support python2
* All RGW users are now retrieved by the suggested `admin/user?list` endpoint.
* A new class method `_get_user_quota` is added to get the user defined quota based on the retrieved list of users.

1. The bucket_quota object is part of a bucket dict. Therefore I suggest keeping the extraction of the bucket quota details in the `_get_bucket_usage` method. (Otherwise we have to create anther loop).I have removed the user quota part from the method. 

Example of a bucket dict to clarify on the quota object: 

```python
{'bucket': 'test',
 'bucket_quota': {'check_on_raw': False,
                  'enabled': False,
                  'max_objects': -1,
                  'max_size': -1,
                  'max_size_kb': 0},
 'explicit_placement': {'data_extra_pool': '',
                        'data_pool': '',
                        'index_pool': ''},
 'id': 'd371c044-13ce-4e68-93a2-5a52522609dc.322449118.1',
 'index_type': 'Normal',
 'marker': 'd371c044-13ce-4e68-93a2-5a52522609dc.322449118.1',
 'master_ver': '0#0',
 'max_marker': '0#',
 'mtime': '2019-10-21 07:18:52.661840Z',
 'num_shards': 0,
 'owner': 'test$test_admin',
 'placement_rule': 'default-placement',
 'tenant': 'test',
 'usage': {},
 'ver': '0#1',
 'zonegroup': '5753ccb2-dc28-4dc9-988f-5cc866a01c5b'}
 ```

3. I've completely separated the user quota from the buckets by adding the `_get_user_quota` method

**Comment by danielpalstra** [comment]
Please let me know what you think so I can squash commits.

**Comment by k0ste** [comment]
Nice! I think you also should implement compatible function for users list, please take a look https://github.com/cernceph/ceph-scripts/blob/master/tools/s3_quota_notice.py#L123-L137 for what I mean.

**Comment by danielpalstra** [comment]
I can add it, but I won't be able to test it, since we've upgraded to Nautilus (14.2.x). Is this something you can add yourself?

**Comment by k0ste** [comment]
The `user?list` method is not a replacement for `metadata/user`.
You should be able to test it with this shell snippet (on my Luminous 12.2.13 it's works fine).

```shell
#!/bin/bash
s3_access_key=""
s3_secret_key=""
s3_host=""
query="admin/metadata/user"
method="GET"
date=$(date -R -u)
header="${method}\n\n\n${date}\n/${query}"
sig=$(echo -en ${header} | openssl sha1 -hmac ${s3_secret_key} -binary | base64)

curl -s -H "Date: ${date}" \
-H "Authorization: AWS ${s3_access_key}:${sig}" \
-H "Host: ${s3_host}" \
-X ${method} \
"https://${s3_host}/${query}" | jq
```

**Comment by danielpalstra** [comment]
I've looked in to your example and just tested the metadata method. I get the same list of users as the `user?list` method. No extra data is added. What are you suggesting to change?

**Comment by k0ste** [comment]
I suggest to use this method (metadata) as backward compatible with ancient versions of Ceph, i.g. if `['keys']` is not present in response of `user?list`.

**Comment by k0ste** [comment]
@danielpalstra after some merges your branch should be rebased before merge this PR.

**Comment by danielpalstra** [comment]
I've changed the retrieval of the rgw users to support ancient versions of Ceph. I've also rebased to the latest master and squashed my own commits.

**Comment by blemmenes** [comment]
Sweet! I'll take a look.

Thanks,
Berant

**Comment by k0ste** [comment]
> I've changed the retrieval of the rgw users to support ancient versions of Ceph. I've also rebased to the latest master and squashed my own commits.

I was test it, and it's works. But current usage of quota per user still missed, example what I mean.

https://github.com/cernceph/ceph-scripts/blob/master/tools/s3_quota_notice.py#L140-L152

**Comment by danielpalstra** [comment]
I've finished the project that depends on this exporter. I won't be making changes to this exporter anytime soon. I suggest to merge this pull request and create a new issue with the new functionality.

**Comment by blemmenes** [comment]
Daniel,

I'm good with that, thank you for contributing, it is appreciated!

Thanks,
Berant

**Pull request merged**
